### ISSUE TITLE
Please tell me how to use fastgltf/0.5.0 with FASTGLTF_DOWNLOAD_SIMDJSON=ON.

### ISSUE THREAD

**Issue by toge** [spnda/fastgltf#22]
I met a compilation error on fastgltf/0.5.0 with FASTGLTF_DOWNLOAD_SIMDJSON=ON.
It works well on fastgltf/0.4.0.

I think this error is due to following commit:
https://github.com/spnda/fastgltf/commit/41f1793d848297fa6aa480402a9ec7e68a96a712

How to use fastgltf/0.5.0 with FASTGLTF_DOWNLOAD_SIMDJSON=ON?
Is it needed to prepare CMakeLists.txt wrapper?

**Comment by spnda** [comment]
`FASTGLTF_DOWNLOAD_SIMDJSON` is `ON` by default, and therefore should work. The relevant change doesn't change anything about the download functionality.

Are you perhaps referring to setting it to `OFF`, so that you can supply a custom version of simdjson? If so, you'll just need to make a `simdjson::simdjson` target available before including fastgltf.

**Comment by toge** [comment]
@spnda 
Sorry, it's my mistake.

I met a compilation error on fastgltf/0.5.0 with FASTGLTF_DOWNLOAD_SIMDJSON=OFF.
Error messages is followings:
```
src/base64.cpp:46:10: fatal error: simdjson.h: No such file or directory
   46 | #include "simdjson.h"
      |          ^~~~~~~~~~~~
```

**Comment by spnda** [comment]
Is that all? Then your `simdjson::simdjson` target is missing the include directory. Can you show how that target is configured?

**Comment by spnda** [comment]
Even though there was no response, this issue has long been fixed in your case with conan (see conan-io/conan-center-index#18301). Furthermore, with the recent commit https://github.com/spnda/fastgltf/commit/3dd326efb089f66ca393a9cc68d07df42ba82fbd the code to link to simdjson has been refactored and now also covers the case you were having an issue with. The patch used with conan is now unnecessary.
